-- MySQL Script generated by MySQL Workbench
-- Wed Jun 21 16:20:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Friendships
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Friendships
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Friendships` DEFAULT CHARACTER SET utf8 ;
USE `Friendships` ;

-- -----------------------------------------------------
-- Table `Friendships`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Friendships`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Friendships`.`Friendships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Friendships`.`Friendships` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Friendships_Users_idx` (`User_id` ASC),
  INDEX `fk_Friendships_Users1_idx` (`friend_id` ASC),
  CONSTRAINT `fk_Friendships_Users`
    FOREIGN KEY (`User_id`)
    REFERENCES `Friendships`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friendships_Users1`
    FOREIGN KEY (`friend_id`)
    REFERENCES `Friendships`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
