Create Database if NOT EXISTS 'Mydb'
-- MySQL Script generated by MySQL Workbench
-- Mon Jun 26 13:20:05 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Mydb` DEFAULT CHARACTER SET utf8 ;
USE `Mydb` ;

-- -----------------------------------------------------
-- Table `Mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `First_name` VARCHAR(255) NULL,
  `Last_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mydb`.`Others`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mydb`.`Others` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Stuff` VARCHAR(255) NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Others_Users_idx` (`User_id` ASC),
  CONSTRAINT `fk_Others_Users`
    FOREIGN KEY (`User_id`)
    REFERENCES `Mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
