-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 12:07:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fullfriendsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fullfriendsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullfriendsdb` DEFAULT CHARACTER SET utf8 ;
USE `fullfriendsdb` ;

-- -----------------------------------------------------
-- Table `fullfriendsdb`.`fullfriends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullfriendsdb`.`fullfriends` (
  `idfullfriends` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `occupation` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`idfullfriends`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
